// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXG_9x9s9j3m7q3zqpRm9eLZZSZKsC-UQ',
    appId: '1:772283572199:web:00eba6a3e6150ae18a6742',
    messagingSenderId: '772283572199',
    projectId: 'todo-firebase-25902',
    authDomain: 'todo-firebase-25902.firebaseapp.com',
    storageBucket: 'todo-firebase-25902.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZAsGgLttUkdHMBZba8GJLi507I-_u5n4',
    appId: '1:772283572199:android:cd9108d49585300c8a6742',
    messagingSenderId: '772283572199',
    projectId: 'todo-firebase-25902',
    storageBucket: 'todo-firebase-25902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxGFnMutyEPO5lrrtvNCYXdg57VHZ1BAU',
    appId: '1:772283572199:ios:e894bd60e96ac3848a6742',
    messagingSenderId: '772283572199',
    projectId: 'todo-firebase-25902',
    storageBucket: 'todo-firebase-25902.appspot.com',
    iosClientId: '772283572199-hb0g23nf5ds57c15fpd1vb2lg058fp0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxGFnMutyEPO5lrrtvNCYXdg57VHZ1BAU',
    appId: '1:772283572199:ios:e894bd60e96ac3848a6742',
    messagingSenderId: '772283572199',
    projectId: 'todo-firebase-25902',
    storageBucket: 'todo-firebase-25902.appspot.com',
    iosClientId: '772283572199-hb0g23nf5ds57c15fpd1vb2lg058fp0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );
}
